"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path

# --- 1. 基本設定 ---
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-vvyo@62z3nv3jc@jtf7r1_^=b$50wxwa@gcd$4d-6@8)l!o)#h'
DEBUG = True
ALLOWED_HOSTS = []

# --- 2. アプリケーション定義 ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'steppia_app', # メインアプリ
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# --- 3. データベース設定 ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- 4. パスワードバリデーション ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- 5. 言語・時刻設定 ---
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True

# --- 6. 静的ファイル・メディア設定 ---
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ユーザーアップロード画像（コンサルタント写真等）の保存先
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- 7. 認証・リダイレクト設定 ---
# 🆕 エラー解消ポイント: name='menu' に合わせる

# ログインに成功したらメニュー画面へ
LOGIN_REDIRECT_URL = 'menu'

# ログアウトしたらメニュー画面（またはログイン画面）へ
LOGOUT_REDIRECT_URL = 'menu'

# 🆕 追加：ログインが必要な時に自動で飛ばす先を指定
# これを入れないと Django は勝手に /accounts/login/ を探してしまいます
LOGIN_URL = 'login'