# Generated by Django 6.0 on 2025-12-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓')),
                ('first_name', models.CharField(max_length=100, verbose_name='名')),
                ('last_name_kana', models.CharField(max_length=100, verbose_name='せい')),
                ('first_name_kana', models.CharField(max_length=100, verbose_name='めい')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
            ],
        ),
    ]
