# Generated by Django 6.0 on 2025-12-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steppia_app', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConsultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField(verbose_name='相談内容')),
                ('ai_response', models.TextField(verbose_name='AIの回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='相談日時')),
            ],
        ),
        migrations.CreateModel(
            name='AIConsultTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='よくある質問')),
                ('answer', models.TextField(verbose_name='回答内容')),
            ],
        ),
    ]
