# Generated by Django 5.2.1 on 2025-12-22 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steppia_app', '0004_aiconsultlog_aiconsulttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='仕事のタイトル')),
                ('company', models.CharField(max_length=100, verbose_name='会社名')),
                ('location', models.CharField(max_length=100, verbose_name='勤務地')),
                ('salary', models.CharField(max_length=100, verbose_name='給与')),
                ('description', models.TextField(verbose_name='仕事の内容')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied At')),
                ('status', models.CharField(default='Wait for contact', max_length=50, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steppia_app.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'unique_together': {('user', 'job')},
            },
        ),
    ]
