# Generated by Django 5.2.1 on 2025-12-22 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steppia_app', '0005_job_applications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='就労日')),
                ('hours', models.FloatField(verbose_name='就労時間')),
                ('earnings', models.IntegerField(verbose_name='総支給額')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steppia_app.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'お仕事ログ',
            },
        ),
    ]
