# Generated by Django 5.2.1 on 2025-12-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steppia_app', '0006_worklog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': '会員情報'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name_kana',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name_kana',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='daily_wage',
            field=models.IntegerField(default=0, verbose_name='賃金日額'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='姓'),
        ),
    ]
