# Generated by Django 5.2.1 on 2025-12-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steppia_app', '0007_alter_member_options_remove_member_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='住所'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='first_name_kana',
            field=models.CharField(default=1, max_length=100, verbose_name='めい'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='last_name_kana',
            field=models.CharField(default='', max_length=100, verbose_name='せい'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='電話番号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worklog',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='aiconsultlog',
            name='ai_response',
            field=models.TextField(verbose_name='AI의回答'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='姓'),
        ),
    ]
