# Generated by Django 5.2.1 on 2025-12-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steppia_app', '0008_member_address_member_first_name_kana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_roulette_date',
            field=models.DateField(blank=True, null=True, verbose_name='最後にルーレットを回した日'),
        ),
        migrations.AlterField(
            model_name='aiconsultlog',
            name='ai_response',
            field=models.TextField(verbose_name='AIの回答'),
        ),
    ]
