# Generated by Django 5.2.1 on 2025-12-24 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steppia_app', '0009_member_last_roulette_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(max_length=100, verbose_name='景品名')),
                ('won_at', models.DateTimeField(auto_now_add=True, verbose_name='獲得日時')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '獲得クーポン',
            },
        ),
    ]
