# Generated by Django 6.0 on 2025-12-25 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steppia_app', '0011_member_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconsultlog',
            options={'verbose_name': 'AI相談ログ', 'verbose_name_plural': 'AI相談ログ'},
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': '応募履歴・進捗', 'verbose_name_plural': '応募履歴・進捗'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': '獲得クーポン', 'verbose_name_plural': '獲得クーポン'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '会員情報', 'verbose_name_plural': '会員情報'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'スケジュール', 'verbose_name_plural': 'スケジュール'},
        ),
        migrations.AlterModelOptions(
            name='worklog',
            options={'verbose_name': 'お仕事ログ', 'verbose_name_plural': 'お仕事ログ'},
        ),
        migrations.AddField(
            model_name='aiconsultlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='applications',
            name='current_step',
            field=models.IntegerField(default=1, verbose_name='現在のステップ'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='応募日時'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steppia_app.job', verbose_name='応募先企業'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(default='連絡待ち', max_length=50, verbose_name='選考ステータス'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='detail',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='steppia_app.job', verbose_name='求人'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
