# Generated by Django 5.2.1 on 2025-12-26 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steppia_app', '0012_alter_aiconsultlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
        migrations.AlterModelOptions(
            name='aiconsulttemplate',
            options={'verbose_name': 'AI相談テンプレート', 'verbose_name_plural': 'AI相談テンプレート'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '求人情報', 'verbose_name_plural': '求人情報'},
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
