# Generated by Django 5.2.1 on 2025-12-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steppia_app', '0013_rename_applications_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='assigned_consultant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='担当コンサルタント'),
        ),
    ]
